services:
  - type: web
    name: mini-project-backend
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    preDeployCommand: npx prisma migrate deploy
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: project_signup-signin_db
          property: connectionString
